
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 24 05:35:06 EET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 4;
  public static final int SM = 2;
  public static final int NM = 5;
  public static final int error = 1;
  public static final int AO = 3;
  public static final int EOF = 0;
}

